// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbJL4DptCLzFaiQbwqrB3RD_N-S6WDA0',
    appId: '1:216012171367:web:afd062d049daf26de2ccc2',
    messagingSenderId: '216012171367',
    projectId: 'fcmflutter-aabbd',
    authDomain: 'fcmflutter-aabbd.firebaseapp.com',
    storageBucket: 'fcmflutter-aabbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7GG33-bu6k42hYq5mbghUZMDta49Yi-k',
    appId: '1:216012171367:android:5d8a64bca79d5f4be2ccc2',
    messagingSenderId: '216012171367',
    projectId: 'fcmflutter-aabbd',
    storageBucket: 'fcmflutter-aabbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBytfA9QV54Sf8ywCLjjgMkZ_p_wiqPszQ',
    appId: '1:216012171367:ios:d2ce6c82fbc6e3a4e2ccc2',
    messagingSenderId: '216012171367',
    projectId: 'fcmflutter-aabbd',
    storageBucket: 'fcmflutter-aabbd.appspot.com',
    iosBundleId: 'com.flutter.fcm.fcmflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBytfA9QV54Sf8ywCLjjgMkZ_p_wiqPszQ',
    appId: '1:216012171367:ios:874c001b028eb5f6e2ccc2',
    messagingSenderId: '216012171367',
    projectId: 'fcmflutter-aabbd',
    storageBucket: 'fcmflutter-aabbd.appspot.com',
    iosBundleId: 'com.flutter.fcm.fcmflutter.RunnerTests',
  );
}
